Add frame of project
frontend-park-mail-ru/2021_1_DuckLuck pull request #1
Opened 2021-02-22 14:11 UTC by Tullerpeton

Сделал каркас кода:

1. Сущность страниц храниться во view и страница рисуется через `render()`
2. Модуль `Ajax` - `AjaxWithFetch`

2021-02-22 20:05 UTC, tmible requested changes
Симпатично однако

2021-02-22 20:05 UTC, tmible commented on ozon/package.json
> +  "dependencies": {
Тут точно ничего, что должно быть в dev-dependencies, нет? (если что, это `npm install --save-dev`)

2021-02-22 20:05 UTC, tmible commented on ozon/package.json
> +  "version": "1.0.0",
Смело)

2021-02-22 20:05 UTC, tmible commented on ozon/src/index.html
> +  <script defer src="/modules/Ajax/Ajax.js"></script>
Я, конечно, понимаю, что страничка небольшая, но почему `defer`?

2021-02-22 20:05 UTC, tmible commented on ozon/src/views/ProfilePage/ProfilePage.css
> +.profile__text {
Это что, [БЭМ](https://ru.bem.info/methodology/quick-start/)?

2021-02-22 20:05 UTC, tmible commented on ozon/src/styles.css
> +a, input {
Используй классы

2021-02-22 20:05 UTC, tmible commented on ozon/src/main.js
> +const {ajaxPutUsingFetch, ajaxDeleteUsingFetch, ajaxPostUsingFetch, ajaxGetUsingFetch} = globalThis.AjaxModule;
Не понял, зачем импорт и в html (и зачем он там вообще), и тут?

2021-02-22 20:05 UTC, tmible commented on ozon/src/modules/Ajax/Ajax.js
> +    class AjaxModule {
Господи, столько слов ajax — я испугался

2021-02-22 20:05 UTC, tmible commented on ozon/src/main.js
> +function homePage() {
Почему не стрелочные?

2021-02-22 20:05 UTC, tmible commented on ozon/src/views/BasePage.js
> +export class BasePage {
Чёт какой-то класс бесполезный. Я вижу во всех наследниках одни и те же приватные поля, копипасту конструктора и одинаковый набор методов. Базовый класс же как раз для того, чтобы копипасту в него запрятать и не множить, а необходимый набор методов задокументировать. Может, даже стандартизировать, если возможно

2021-02-22 20:05 UTC, tmible commented on ozon/src/views/HomePage/HomePage.js
> +        super ();
Чёта скобочки отъехали

2021-02-22 20:05 UTC, tmible commented on ozon/src/views/HomePage/HomePage.js
> +            .map((menuKey) => {
Не совсем понял здесь задумку. Зачем ключи конфига менять?

2021-02-22 20:05 UTC, tmible commented on ozon/src/views/SignupPage/SignupPage.js
> +        back.href = '/menu';
Стоп, куда отправляешь? В конфиге нет такого урла

2021-02-22 20:05 UTC, tmible commented on ozon/src/main.js
> +    form.addEventListener('submit', (evt) => {
Почему это здесь, понимаю. Почему `appendChild()` тоже здесь, не очень. Похоже на задачу метода `render()`

2021-02-22 20:05 UTC, tmible commented on ozon/src/main.js
> +    const form = page.render();
А тут добавления в DOM нет совсем? Или я что-то упустил?

2021-02-22 20:05 UTC, tmible commented on ozon/src/main.js
> +            url: '/signup',
Кстати, документация api у вас есть? Очень полезная штука

2021-02-22 20:05 UTC, tmible commented on ozon/src/main.js
> +                    alert(error);
Надеюсь, алерты с нами не надолго........

2021-02-22 20:05 UTC, tmible commented on ozon/src/main.js
> +            const profile = new ProfilePage(application);
Как насчёт сначала рендерить страничку, а потом по мере поступления данных, наполнять её?

2021-02-23 17:13 UTC, Tullerpeton commented on ozon/package.json
> +  "dependencies": {
Добавил все зависимости, которые относятся к разработке в `devDependencies`

2021-02-23 17:14 UTC, Tullerpeton commented on ozon/package.json
> +  "version": "1.0.0",
Поменял на версию 0.0.1

2021-02-23 17:14 UTC, Tullerpeton commented on ozon/src/index.html
> +  <script defer src="/modules/Ajax/Ajax.js"></script>
Как я понял `defer` для того, чтобы асинхронно модули загрузить, но выполнить в строгом порядке
Но я убрал подключение этого модуля

2021-02-23 17:14 UTC, Tullerpeton commented on ozon/src/main.js
> +const {ajaxPutUsingFetch, ajaxDeleteUsingFetch, ajaxPostUsingFetch, ajaxGetUsingFetch} = globalThis.AjaxModule;
В html убрал импорт

2021-02-23 17:14 UTC, Tullerpeton commented on ozon/src/modules/Ajax/Ajax.js
> +    class AjaxModule {
Теперь только сам класс `AjaxModule`, и в каждом методе нет 'ajax....'

2021-02-23 17:14 UTC, Tullerpeton commented on ozon/src/main.js
> +function homePage() {
Заменил на стрелочные

2021-02-23 17:14 UTC, Tullerpeton commented on ozon/src/views/BasePage.js
> +export class BasePage {
Вынес общую логику в `BasePage`

2021-02-23 17:14 UTC, Tullerpeton commented on ozon/src/main.js
> +    form.addEventListener('submit', (evt) => {
Вынес `appendChild()` в `render()`

2021-02-23 17:14 UTC, Tullerpeton commented on ozon/src/main.js
> +    const form = page.render();
Добавил добавление в `DOM` в методе `render()`

2021-02-23 17:14 UTC, Tullerpeton commented on ozon/src/main.js
> +            const profile = new ProfilePage(application);
Выделил функцию `renderData()` у `ProfilePage` которая заполняет данные. Через `fetch` сначала получаю код и если запрос успешен, то рендерю страницу, а затем загружаю данные

2021-02-23 17:16 UTC, Tullerpeton commented
Внёс исправления и добавил сервер

2021-02-23 19:20 UTC, tmible commented on ozon/src/index.html
> +  <script defer src="/modules/Ajax/Ajax.js"></script>
Как раз наоборот. `defer` ждёт загрузку страницы и только потом грузит скрипт. В принципе, [здесь](http://htmlbook.ru/html/script) инфы достаточно. Ну и в целом сайтик полезный

2021-02-23 19:20 UTC, tmible commented on ozon/package.json
> +  "version": "1.0.0",
Да это, в общем, не обязательно было

2021-02-23 19:21 UTC, tmible commented on ozon/src/main.js
> +            const profile = new ProfilePage(application);
То, что нужно

2021-02-23 19:33 UTC, tmible commented on ozon/src/modules/Ajax/Ajax.js
> +    class AjaxModule {
Я просто боюсь этого слова. Если вам так удобно, пишите так

2021-02-23 19:48 UTC, tmible requested changes
Так, кажется, это не тот сервер. Сервер фронтенда должен выдавать страничку со всем сопутствующим и всё. Поскольку это SPA дальше всё живёт своей жизнью в браузере. Такая жизнь подразумевает асинхронные запросы на сервер, только уже на сервер бэкенда.

2021-02-23 19:48 UTC, tmible commented on ozon/server/index.js
> +const childProc = require('child_process');
Так, будем по-модному писать. Всё через `import`

2021-02-23 19:48 UTC, tmible commented on ozon/server/index.js
> +app.post('/signup', function (req, res) {
Стрелочные, пожалуйста

2021-02-23 19:48 UTC, tmible commented on ozon/src/views/BasePage.js
> +    _parent;
А что теперь некрасивые `_` вместо суперских `#`?

2021-02-23 19:52 UTC, Tullerpeton commented on ozon/src/views/BasePage.js
> +    _parent;
Так это `protected` [атрибуты класса](https://learn.javascript.ru/private-protected-properties-methods). Чтобы унаследованные классы имели к ним доступ. А `#` - это `private`

2021-02-23 20:11 UTC, tmible commented on ozon/src/views/BasePage.js
> +    _parent;
Жуть, ну ладно. Если хочешь настоящую инкапсуляцию сделать, дам спойлер небольшой: можно писать на TypeScript. Строго по желанию и по возможностям

2021-02-24 14:57 UTC, Tullerpeton commented
Исправил:
1. Модное подключение модулей через `import`
2. Изменил сервер, теперь он выдаёт только `index.html` 

`API` пока нету, как и самого сервера бэкенда

2021-02-25 16:19 UTC, tmible approved these changes

2021-02-25 16:20 UTC, merged