Ozon 8 profile page
frontend-park-mail-ru/2021_1_DuckLuck pull request #13
Opened 2021-03-08 20:53 UTC by lev4rT

Прикрутил  валидатор. Поправил различные ошибки на страничке.

2021-03-08 21:57 UTC, tmible requested changes
Так всё-таки `firstName` и `lastName` актуальны или вы их выпилили?

2021-03-08 21:57 UTC, tmible commented on ozon/src/main.js
> +const defaultAvatarURL = 'http://localhost:8100/avatar/default.png'
Это новый вариант или это уйдёт из-за конфликта с develop? Там уже есть такие константы в другом месте

2021-03-08 21:57 UTC, tmible commented on ozon/src/main.js
> +        // const lastName = document.getElementById('last-name').value.trim();
Можно удалять, вроде, нет?

2021-03-08 21:57 UTC, tmible commented on ozon/src/utils/validator.js
> +    return /^[a-zA-Z](.[a-zA-Z0-9]*)$/.test(input.value);
Не понял: зачем тут `.` в регулярке?

2021-03-08 21:57 UTC, tmible commented on ozon/src/utils/validator.js
> +    return /^[a-zA-Zа-яА-Я'][a-zA-Zа-яА-Я-' ]+[a-zA-Zа-яА-Я']?$/.test(input.value);
Начать имя с `'` можно, получается?
Почему в конце `?`. Я так понял, последние `[]` нужны, чтобы на пробел не заканчивалось имя. Тогда `?` всё портит.
Длиной в одну букву нельзя, получается?

2021-03-08 21:57 UTC, tmible commented on ozon/src/utils/validator.js
> +    console.log(isValid);
Убирай

2021-03-08 21:57 UTC, tmible commented on ozon/src/views/ProfilePage/ProfilePage.js
> +        if (avatar === '') {
Мб тут лучше вызвать `renderAvatar`? А то прямо тот же самый код

2021-03-08 21:57 UTC, tmible commented on ozon/src/main.js
> +let isPageWasOpened = false
Поясни логику, пожалуйста

2021-03-08 21:57 UTC, tmible commented on ozon/src/main.js
> +    if (!isPageWasOpened) {
Ох, вложенность, вложенность. Лучше сделать что-то типа
```
if (isPageWasOpened) {
  return;
}
```

2021-03-08 21:57 UTC, tmible commented on ozon/src/main.js
> +                        }
Вроде, то же самое в `renderData()` уже есть

2021-03-08 21:57 UTC, tmible commented on ozon/src/main.js
> +    if (!isPageWasOpened) {
Или, стоп, это я не понял логики ветвления тут

2021-03-08 22:15 UTC, lev4rT commented on ozon/src/main.js
> +let isPageWasOpened = false
У меня была ошибка, что каждый раз при заходе на страницу навешивался обработчик. Таким образом, кол-во навешанных обработчиков зависело от того, сколько раз пользователь заходил на страницу. Решил избавиться от этого вот таким способом

2021-03-09 05:13 UTC, tmible requested changes

2021-03-09 05:13 UTC, tmible commented on ozon/src/utils/validator.js
> +    return /^[a-zA-Z]([a-zA-Z0-9]*)$/.test(input.value);
Можно группу убрать

2021-03-09 05:13 UTC, tmible commented on ozon/src/utils/validator.js
> +    return /^[a-zA-Zа-яА-Я]+$/.test(input.value);
Ох, не повезло апострофникам. Ну и бог с ними

2021-03-09 05:13 UTC, tmible commented on .gitignore
> +>>>>>>> 37215e718cb2cecbeeac00c14c29c91a70ff014d
Что за конфликты повылезали?

2021-03-09 05:13 UTC, tmible commented on package.json
> +    "start-dev": "webpack --watch & node ozon/server/index.mjs",
Опять конфликты какие-то?

2021-03-09 05:13 UTC, tmible commented on ozon/src/main.js
> +let isPageWasOpened = false
Здорово, что следишь за этим: это важно.
Мб тогда просто добавлять eventlistener на саму форму только после рендера в самой вьюхе? В пользу этого говорит то, что, пока это тут, тут же идёт сетевой запрос именно этой вьюхи. Архитектурно его тут не должно быть

2021-03-09 05:13 UTC, tmible commented on ozon/src/views/ProfilePage/ProfilePage.js
> - */
Из-за конфликтов пропало? Ты как коммит сделал?

2021-03-09 07:02 UTC, lev4rT commented on ozon/src/main.js
> +let isPageWasOpened = false
Спасибо, это именно то, что я и хотел сделать

2021-03-09 11:38 UTC, tmible requested changes
Ой, а логов-то, а snake_caseов-то! Убирай

2021-03-09 11:38 UTC, tmible commented on ozon/src/views/ProfilePage/ProfilePage.js
> +        const form = document.getElementsByClassName('profile-credentials__form')[0]
На ней, вроде, айдишник висит. Не нравится?

2021-03-09 12:33 UTC, lev4rT commented
Сней кейсы поправил, но не везде. С ними такая трабла, что ответ с самого сервера приходит с ними. Надо будет в будущем подправить это на бэкенде.

2021-03-09 13:59 UTC, tmible approved these changes

2021-03-09 14:00 UTC, merged