Mvp arch
frontend-park-mail-ru/2021_1_DuckLuck pull request #25
Opened 2021-03-29 20:26 UTC by lev4rT

Попытался пределать проект мод архитектуру MVP. В середине процесса понял, что без роутинга будет сложнее, поэтому добавил и его (пока только базовый).

2021-03-30 22:00 UTC, tmible requested changes
Я там где-то написал про singleton роутер. Обновляю свои слова: готов с ним согласиться, только синтаксис с постоянным `new` мне не нрав.

Поскольку изменения по большей части шаблонные, смотри, пожалуйста, каждый комментарий не только там, где он написан, но и в подобных местах, в других файлах!

2021-03-30 22:00 UTC, tmible commented on ozon/src/Router.js
> +        if (Router.__instance) {
А что, `#instance` уже не нравится?

2021-03-30 22:00 UTC, tmible commented on ozon/src/Router.js
> +        if (window.location.pathname !== path) {
Убери один уровень вложенности

2021-03-30 22:00 UTC, tmible commented on ozon/src/Router.js
> +            // });
Комментарии убирай

2021-03-30 22:00 UTC, tmible commented on ozon/src/bus.js
> +            .filter(function(listener) {
Почему не стрелочная?(

2021-03-30 22:00 UTC, tmible commented on ozon/src/bus.js
> +        this.listeners[event].forEach(function(listener) {
То же

2021-03-30 22:00 UTC, tmible commented on ozon/src/views/BaseView.js
> +     * @param {Object} el HTML element
Что такое `el`? И что с ним происходит? Я пока не могу понять

2021-03-30 22:00 UTC, tmible commented on ozon/src/views/BaseView.js
> +     * @param {Object} el HTML element
В смысле нейминг надо поправить точно. Мб ещё JSDoc

2021-03-30 22:00 UTC, tmible commented on ozon/src/views/BaseView.js
> +    get active() {
Ну так мб тогда `isActive`?

2021-03-30 22:00 UTC, tmible commented on ozon/src/views/HomeView/HomeView.js
> +        if (HomeView.__instance) {
Вот это уже какая-то антипаттерн сторона синглтона. Один раз зашёл на страничку, и она теперь в памяти навсегда?

2021-03-30 22:00 UTC, tmible commented on ozon/src/views/HomeView/HomeView.js
> +     * @param {Object} config configuration which will use to render this page
Где? Что?

2021-03-30 22:00 UTC, tmible commented on ozon/src/views/HomeView/HomeView.js
> +    render = () => {
Так, я думаю, стоит определиться, как объявлять методы. Чтобы везде одинаково было

2021-03-30 22:00 UTC, tmible commented on ozon/src/views/LoginView/LoginView.js
> +        const blind = this.cache.getElementsByClassName('blind')[0];
Один раз используется. Зачем константа?

2021-03-30 22:00 UTC, tmible commented on ozon/src/views/LoginView/LoginView.js
> +            (new Router()).return();
Жутко. Почему не создать экземпляр и передать его всем?

2021-03-30 22:00 UTC, tmible commented on ozon/src/views/LoginView/LoginView.js
> +            Bus.emit('login-send-data' );
Один ивентбас на всех -- плохая идея. Так любой класс может вызвать событие, на которое подписалась эта view. Нам же нужно, чтобы она общалась через ивентбас исключительно со своей моделью

2021-03-30 22:00 UTC, tmible commented on ozon/src/main.js
> +// };
Это что за жесть с комментариями? Ты размер диффа видел? Если код не нужен -- выкидывай его. Если нужен, раскомментируй

2021-03-30 22:00 UTC, tmible commented on ozon/src/main.js
> +Bus.on('signup-emit-result', signupPresenter.processSignupResult);
Что-то мне вот этот весь мусор здесь не нравится. Давай всё это в презентер спрячем. Если с созданием вью и модели тут ещё можно согласиться (ну такое), то вот подписка на события (с учётом того, что ивентбас не глобальный) точно переезжает в зону ответственности презентера

2021-03-30 22:00 UTC, tmible commented on ozon/src/presenters/ProductPresenter.js
> +        this._view._itemID = id;
window.location менять не надо?

2021-03-30 22:00 UTC, tmible commented on ozon/src/views/ProductsView/ProductsView.js
> +        this._presenter.loadProducts(this._currentPage);
Кажется, что это должно происходить через ивентбас. Где этот метод используется?

2021-03-30 22:00 UTC, tmible commented on ozon/src/views/ProductView/ProductView.js
> +        this._presenter.loadProduct(this._itemID);
Ещё мне не нравится, что есть обращение к `_prsenter`, но внятной его инициализации нет

2021-03-30 22:00 UTC, tmible commented on ozon/src/models/LoginModel.js
> +                Bus.emit('login-emit-result', 'failure to login');
Вообще, вот эти имена событий в enum какой-нибудь вынести бы, или во что-то типа того

2021-03-30 22:00 UTC, tmible commented on ozon/src/models/LoginModel.js
> +                Bus.emit('login-emit-result', 'failure to login');
Так же, как и коды ответов во втором параметре

2021-03-30 22:00 UTC, tmible commented on ozon/src/models/ProductsModel.js
> +                sort_direction: 'ASC',
А эти параметры не передаются извне и не меняются? Я так понимаю, сейчас этого нет пока, поэтому вполне норм варик просто вынести их в параметра функции с дефолтными значениями

2021-03-30 22:00 UTC, tmible commented on ozon/src/views/ProfileView/ProfileView.js
> +        emailInput.value = email;
Действительно во всех этих методах нужно сохранять DOM элементы в переменные?

2021-03-30 22:00 UTC, tmible commented on ozon/src/views/ProfileView/ProfileView.js
> +        const firstName = this._presenter.getFirstName();
Кстати, я думаю, можно договориться так: гетеры презентера разрешены, вызов методов -- через ивентбас. С другой стороны, почему бы не передавать из модели в презентер, а из него сюда один раз этот объектик с данными из сети и не хранить его вообще нигде?

2021-03-30 22:00 UTC, tmible commented on ozon/src/presenters/ProfilePresenter.js
> +    changeFirstLastName = () => {
Чёт путаница с неймингом. Во вью `changeX`, тут `changeX`, и они совсем о разном

2021-03-30 22:00 UTC, tmible commented on ozon/src/views/ProfileView/ProfileView.js
> +        nameLabel.innerHTML = firstName + ' ' + lastName;
Так, а тут дублирование кода выходит? Есть этот метод, а есть `changeX`, реализующие только часть этого, так?

2021-03-30 22:00 UTC, tmible commented on ozon/src/presenters/ProfilePresenter.js
> +        return this._model.email;
Не понял. Чем отличается от предыдущих двух?

2021-03-30 22:00 UTC, tmible commented on ozon/src/models/ProfileModel.js
> +        this._checkAuthModel = new CheckAuthModel();
Нет, стоп. Почему так? Есть вью профиля -- есть модель профиля. Это что за покемоны?

2021-03-30 22:00 UTC, tmible commented on ozon/src/models/FLNameModel.js
> +        });
Ошибок не бывает?

2021-03-30 22:00 UTC, tmible commented on ozon/src/models/AvatarModel.js
> +            });
Такой же код был уже в этом классе

2021-04-01 18:58 UTC, lev4rT commented on ozon/src/views/HomeView/HomeView.js
> +    render = () => {
Да, изначально так и планировалось, что рендер наследуется от базовго класса и всегда без параметров. Но на каком-то этапе понял, что вот например для этой функции нужен некий "конфиг" - список ссылок, которые надо отобразить. Вынес этот конифг в отдельный файл

2021-04-01 19:00 UTC, lev4rT commented on ozon/src/views/LoginView/LoginView.js
> +        const blind = this.cache.getElementsByClassName('blind')[0];
Думал так читается лучше, чем одна длинная портянка с доступам к полям/элементам по индексу

2021-04-01 19:32 UTC, lev4rT commented on ozon/src/views/LoginView/LoginView.js
> +            Bus.emit('login-send-data' );
Как тогда быть? Можно ли хранить один Bus в модели, презентере и вьюхе?

2021-04-03 03:48 UTC, lev4rT commented on ozon/src/views/HomeView/HomeView.js
> +        if (HomeView.__instance) {
В требованиях к ДЗ сказано: "Каждый момент времени должны быть активны только необходимые Views, кроме этого все они должны кэшироваться и не создаваться лишний раз и без надобности". Я думал под этим как раз и имеется в виду реализованное мною

2021-04-03 03:52 UTC, lev4rT commented on ozon/src/views/LoginView/LoginView.js
> +            Bus.emit('login-send-data' );
И ещё тогда непонятно как вызвать события для других контроллеров, если ивент бас не один на всех

2021-04-03 04:45 UTC, lev4rT commented on ozon/src/views/ProfileView/ProfileView.js
> +        const firstName = this._presenter.getFirstName();
Думаю не очень хорошая идея, всё же по канону в MVP данные хранятся в модели

2021-04-03 04:58 UTC, lev4rT commented on ozon/src/presenters/ProfilePresenter.js
> +        return this._model.email;
Смена email`а пока не сделана, т.к. это может вызвать проблемы на сервере

2021-04-03 05:01 UTC, lev4rT commented on ozon/src/views/LoginView/LoginView.js
> +            Bus.emit('login-send-data' );
На лекции рассказывалось про eventBus одиночку
https://frontend.tech-mail.ru/slides/s5/index.html#56

2021-04-03 05:07 UTC, lev4rT commented on ozon/src/views/ProductView/ProductView.js
> +        this._presenter.loadProduct(this._itemID);
Есть сеттер в базовой вьюхе

2021-04-03 05:08 UTC, lev4rT commented on ozon/src/models/ProfileModel.js
> +        this._checkAuthModel = new CheckAuthModel();
Это фасад. Прочитал про это в одной из рекомндованных на лекции статей

https://habr.com/en/post/276593/

Искать со слов: Фасад — это объект-интерфейс, аккумулирующий

2021-04-03 17:21 UTC, lev4rT commented
Теперь, вроде, выглядит неплохо. Постарался исправить все замечания. Добавил обозначения в нейминге для "модулей" в моделях. Добавил Евент басы для каждой части mvp, вьюхи больше не синглтоны.

2021-04-04 09:04 UTC, tmible commented on ozon/src/views/HomeView/HomeView.js
> +    render = () => {
Я в том смысле, что есть два синтаксических варианта объявления методов класса: `render() {}` и `render = () => {}`

2021-04-04 10:22 UTC, tmible requested changes
Ну прям уже красота получается

На всякий случай продублирую тут общие вопросы:
1) почему где-то `_field`, где-то `#field`? Если мотивация первого варианта -- обозначение приватности, то пусть уж всё `#` будет;
2) я действительно считаю, что конструктор, содержащий только `super()` можно просто опустить. Это (`super()`) и так происходит;

2021-04-04 10:22 UTC, tmible commented on ozon/src/main.js
> +signupView.presenter = signupPresenter;
Вот так уже гораздо лучше! Почему не хочешь убрать это всё в презентер (а последнюю строчку вообще в конструктор вью)? Сейчас есть доступ к вью и моделям прямо отсюда + удаление презентера не означает удаления его вью и модели

2021-04-04 10:22 UTC, tmible commented on ozon/src/models/LoginModel.js
> +    }
Если в конструкторе только вызов `super()` нет необходимости писать конструктор вообще

2021-04-04 10:22 UTC, tmible commented on ozon/src/models/LoginModel.js
> +            url: serverApiPath + urls.loginUrl,
Кстати, мб, первую чать урла пусть один раз сам AjaxModule навешивает? Так меньше всяких связей лишних

2021-04-04 10:22 UTC, tmible commented on ozon/src/models/ProductModel.js
> +    }
Мб всё таки `#item`? Я просто фанат этой фичи

2021-04-04 10:22 UTC, tmible commented on ozon/src/models/SignupModel.js
> +import {serverApiPath, urls} from '../utils/urls/urls';
А зачем весь `urls` импортировать? Нужен же только один

2021-04-04 10:22 UTC, tmible commented on ozon/src/utils/bus/bus.js
> +    static #globalBus
Неплохое решение!

2021-04-04 10:22 UTC, tmible commented on ozon/src/utils/router/Router.js
> +        this.#root.addEventListener('click', function(event) {
Почему не стрелочные?( Тогда и биндить не придётся

2021-04-04 10:22 UTC, tmible commented on ozon/src/models/subModules/AvatarModule.js
> +        }
Одну вложенность убери

2021-04-04 10:22 UTC, tmible commented on ozon/src/models/ProfileModel.js
> +    }
Стоп, а сеттеры вот эти нужны? Данные откуда-то снаружи, не только из модели?

2021-04-04 10:22 UTC, tmible commented on ozon/src/presenters/LoginPresenter.js
> +            this.bus.emit(Events.LoginIncorrectForm, {});
Мб тогда в `bus` заюзать spread syntax и принимать от 0 до бесконечности дополнительных параметров?

2021-04-04 10:22 UTC, tmible commented on ozon/src/presenters/LoginPresenter.js
> +            this.bus.emit(Events.LoginIncorrectForm, {});
Или в принципе здесь же второй можно просто не передавать

2021-04-04 10:22 UTC, tmible commented on ozon/src/views/ProductView/ProductView.js
> +        this.parent.appendChild(this.cache);
Кстати, она не кэшируется, получается?

2021-04-04 10:22 UTC, tmible commented on ozon/src/views/ProductsView/ProductsView.js
> +        this.bus.emit(Events.ProductsLoad, this.ID);
Так, в `ProductView` (24-я строка) просто метод презентера вызывается. Почему тут такие сантименты? Или уж по-хорошему пусть всё остальное тоже через `bus` работает

2021-04-04 10:25 UTC, tmible commented on ozon/src/utils/bus/bus.js
> +            .filter(function(listener) {
Ахахаха, я имел в виду, кстати, почему в 46-й и 57-й строках не стрелочная. Почему методы класса не стрелочные -- понятно. Оно стрелочными и не должны быть

2021-04-04 11:05 UTC, lev4rT commented on ozon/src/models/LoginModel.js
> +            url: serverApiPath + urls.loginUrl,
Не думаю что это хорошая идея, потому что сейчас есть сервер, который запускается на другом порту, который отвечает за файловое хранилище

2021-04-04 11:09 UTC, lev4rT commented on ozon/src/models/SignupModel.js
> +import {serverApiPath, urls} from '../utils/urls/urls';
чё то я хз как это сделать, синтаксис через точку в импорте не работает

2021-04-04 11:22 UTC, lev4rT commented on ozon/src/models/ProfileModel.js
> +    }
Да, ты прав, конкретно в модели профиля эти сеттеры не нужны, всё равно все сеты происходят через специальные методы, которые вызваются по event bus`у. Они лишь вводят в заблуждение. Убрал

2021-04-04 11:26 UTC, lev4rT commented on ozon/src/views/ProductView/ProductView.js
> +        this.parent.appendChild(this.cache);
Да, по сути продукт чаще всего каждый раз обновляется (его id), поэтому не вижу особого смысла кэшировать именно страничку с продуктом и листо продуктов

2021-04-04 22:22 UTC, tmible commented on ozon/src/models/SignupModel.js
> +import {serverApiPath, urls} from '../utils/urls/urls';
А, ну да))00)

2021-04-04 22:34 UTC, tmible requested changes

2021-04-04 22:34 UTC, tmible commented on ozon/src/models/subModules/AvatarModule.js
> +        return this.#avatarURL;
Так наоборот же. Чем меньше кода вложено, тем лучше. Сейчас у тебя 1 строка снаружи, а 11 вложены в `if`

2021-04-04 22:34 UTC, tmible commented on ozon/src/models/subModules/EmailModule.js
> +        return this.#email;
Здесь то же

2021-04-04 22:34 UTC, tmible commented on ozon/src/utils/bus/bus.js
>              .filter(function(listener) {
Так что, стрелочных не будет?

2021-04-04 22:34 UTC, tmible commented on ozon/src/utils/bus/bus.js
>              .filter(function(listener) {
В смысле колбэков

2021-04-05 16:30 UTC, tmible approved these changes

2021-04-05 16:30 UTC, merged