Initial version of CSRF defence
frontend-park-mail-ru/2021_1_DuckLuck pull request #27
Opened 2021-04-06 19:36 UTC by lev4rT

Попытался реализовать то, о чём писал в телеге.

2021-04-07 12:55 UTC, tmible requested changes

2021-04-07 12:55 UTC, tmible commented on ozon/src/main.js
> +AjaxModule.getCSRFToken();
Вот прям сразу он нужен?

2021-04-07 12:55 UTC, tmible commented on ozon/src/models/SignupModel.js
> +        }).catch((err) => {
Зачем параметр добавил?
Кстати, у eslint есть правило no-unused-vars

2021-04-07 12:55 UTC, tmible commented on ozon/src/presenters/ProfilePresenter.js
> +        this.model = new this.ModelClass(this.bus);
Воу, воу, мб просто очищать её??

2021-04-07 12:55 UTC, tmible commented on ozon/src/presenters/BasePresenter.js
> +    }
Не совсем понял, зачем изменения в этом файле

2021-04-07 12:55 UTC, tmible commented on ozon/src/modules/Ajax/Ajax.js
> +const MillisecondsInSecond = 1e3;
Ахахахахахах, да можно просто эти числа использовать)))
Но в целом можно и так

2021-04-07 12:55 UTC, tmible commented on ozon/src/modules/Ajax/Ajax.js
> +const MillisecondsInSecond = 1e3;
Только `MillisecondsInSecond` с маленькой сделай

2021-04-07 12:55 UTC, tmible commented on ozon/src/modules/Ajax/Ajax.js
> +        }).then(async(response) => {
Не понял, что за гибрид async и промисов тут произошёл (вообще) во всём файле

2021-04-09 06:07 UTC, lev4rT commented on ozon/src/presenters/BasePresenter.js
> +    }
Задумка была в том, что в будущем возможно понадобится подмена модели для этого презентера

2021-04-09 06:07 UTC, lev4rT commented on ozon/src/presenters/ProfilePresenter.js
> +        this.model = new this.ModelClass(this.bus);
Да, думаю так лучше будет

2021-04-09 20:35 UTC, lev4rT commented
Тут возникла проблемка с тем, что я не очень удачно декомпозировал по модулями архитектуру в палане запросов. Для получения всех данных о профиля приходилось делать 3 запроса в то время, как все данные можно получить за один. Исправил эту оплошность, но возник вопрос нужно ли сохранять те дополнительные "subModules" для аватара, майла и т.д. или лучше всё вынести в профиль модуля?

2021-04-11 10:20 UTC, tmible commented on ozon/src/modules/Ajax/Ajax.js
> +        // то webpack кидает 22 ошибки во время сборки...
Не, then внутри then -- это норм. Меня микс then и async/await смущает

2021-04-11 10:23 UTC, tmible commented on ozon/src/presenters/BasePresenter.js
> +    }
@lev4rT Как так? Зачем?

2021-04-11 10:27 UTC, tmible commented
> Тут возникла проблемка с тем, что я не очень удачно декомпозировал по модулями архитектуру в плане запросов. Для получения всех данных о профиля приходилось делать 3 запроса в то время, как все данные можно получить за один. Исправил эту оплошность, но возник вопрос нужно ли сохранять те дополнительные "subModules" для аватара, майла и т.д. или лучше всё вынести в профиль модуля?

Решай, как тебе удобнее. Если я правильно понял, сейчас получается так, что эти подмодули служат просто обёрткой над полем (двумя), поэтому лично я не вижу в них особого смысла

2021-04-11 10:27 UTC, tmible approved these changes

2021-04-11 11:09 UTC, merged