Ozon 32 header
frontend-park-mail-ru/2021_1_DuckLuck pull request #29
Opened 2021-04-10 17:54 UTC by DuckLuckBreakout

**Сделано:**

- добавил все необходимое для хедера
- добавил css модули, использовал их только в сущностях, связанных с хедером
- добавил css переменные

Старый мусор из css файлов оставил, буду постепенно удалять, переделывая дизайн наших вьюх под дизайн Озона 

Возникла одна глобальная проблема - мы не понимаем как подключить хедер правильно.
 Хедер существует вообще на всех страницах, всегда одинаковый. Резонно не перестраивать его каждый раз, а объявить его рядом с `application` в [`main.js`](https://github.com/frontend-park-mail-ru/2021_1_DuckLuck/blob/OZON-32-header/ozon/src/main.js):
```js
const header = document.getElementsByTagName('header');
const application = document.getElementById('app');

Router.root = application;

const homeView = new HomeView(application, null, null);

const signupPresenter = new SignupPresenter(application, SignupView, SignupModel);
const loginPresenter = new LoginPresenter(application, LoginView, LoginModel);
const profilePresenter = new ProfilePresenter(application, ProfileView, ProfileModel);
```
Тут возникает следующая проблема - как затриггерить его отрисовку? По аналогии с другими вьюхами поступить не получится, для хедера ведь нет отдельного урла

2021-04-11 10:38 UTC, tmible commented
@DuckLuckBreakout Зачем дизайн Озона? Сделайте свой(
С навбаром примерно так, но по-аккуратнее: ему нужно сделать свой набор MVP, но рендер можно вызвать вручную из `main.js`. По логике работы роутера, он не должен его затирать, так что навбар будет вечно висеть

2021-04-11 11:22 UTC, tmible requested changes

2021-04-11 11:22 UTC, tmible commented on package.json
> +    "style-loader": "^2.0.0",
Не понял. А почему и тут,

2021-04-11 11:22 UTC, tmible commented on package.json
> +    "style-loader": "^2.0.0",
и тут?

2021-04-11 11:22 UTC, tmible commented on ozon/src/views/Common/Img/Img.css
> +    width: var(--img-size-l);
Не на что не намекаю, но у post-css есть макрос `size`

2021-04-11 11:22 UTC, tmible commented on ozon/src/views/HeaderView/HeaderView.css
> +.main {
У вас там использование методологии css в требованиях ко 2-му РК есть

2021-04-11 11:22 UTC, tmible commented on ozon/src/views/HeaderView/HeaderView.css
> +    font-family: var(--font);
Не наследуется что ли?

2021-04-11 11:22 UTC, tmible commented on ozon/src/views/HeaderView/HeaderView.css
> +}
Мб это в общий куда-нибудь вынести?

2021-04-11 11:22 UTC, tmible commented on ozon/src/views/HeaderView/HeaderView.css
> +}
Это, в принципе, тоже

2021-04-12 10:02 UTC, DuckLuckBreakout commented
Дизайн, как минимум пока что, будет озоновский) У них слишком классный хедер, а еще времени не хватит до рк новый дизайн придумать
Для свойств по типу: 
```css
.hidden {
    display: none;
}
```
выделил [`decorators.css`](https://github.com/frontend-park-mail-ru/2021_1_DuckLuck/blob/OZON-32-header/ozon/src/views/decorators.css) на уровне вьюх, не могу сказать, на сколько это правильно, но вроде ему тут норм

2021-04-12 16:13 UTC, tmible approved these changes

2021-04-12 16:20 UTC, merged