Initial version of templated SugnUp page was added.
frontend-park-mail-ru/2021_1_DuckLuck pull request #3
Opened 2021-02-27 16:19 UTC by lev4rT

Прошу проверить пример применения шаблонизатора handlebars

2021-02-28 14:16 UTC, tmible requested changes
Вроде, всё норм, кроме пары мелких замечаний.

Не понимаю, почему вы так сильно паритесь с этим переиспользованием компонентов типа кнопки, ссылки, инпутов. На данном этапе пока ничего кртитичного не вижу. Кстати, мб стоит их попробовать унаследовать от базового класса компонента такого.

Вообще, сейчас они работают норм, потому что их текст просто лепится подряд в `innerHTML`, но всё-таки в браузере единица рендера -- это страница. Я к тому, что пока нет вёрстки страницы, а тем более адаптивной, это переиспользование может быть норм. Но как только добавится дизайн и вёрстка, это будет выглядеть уже не очень. Такие мелочи просто пишутся один раз в файле с разметкой и всё. Чтобы их параметризовать (всё-таки, это, конечно, нужно, но не настолько точечно) при рендере шаблона передаётся объект с данными на всю страницу.

2021-02-28 14:16 UTC, tmible commented on ozon/src/index.html
> +  <script src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.12/handlebars.min.js"></script>
Через npm он не ставится?

2021-02-28 14:16 UTC, tmible commented on package.json
>      "morgan": "^1.9.1"
Кстати, `morgan` разве нужен ещё? Выпилите ненужные зависимости

2021-02-28 14:16 UTC, tmible commented on ozon/src/main.js
> +        console.log(document.getElementsByName('Age'))
Логи убирай

2021-02-28 14:16 UTC, tmible commented on ozon/src/main.js
> +        // TODO: Can i get values here by another way?
А чем этот не устраивает? По-другому можно, наверное, только то же самое, но через `id`

2021-02-28 14:16 UTC, tmible commented on ozon/src/views/SignupPage/SignupPage.js
> +        let objectsToRender = [
Почему `let`?

2021-02-28 19:03 UTC, lev4rT commented
Основной посыл понятен. Пока нет нормальной вёрстки - всё ок. Просто на данном этапе не особо понимаю что ок, а что не ок, опыта в вебе 0. И про "Такие мелочи просто пишутся один раз в файле с разметкой и всё", вроде задача разработать SPA, то есть всё должно создаваться прямо в самом JS (если можно поясни плз как-то этот момент насчёт файла с вёрсткой).

2021-02-28 20:09 UTC, tmible requested changes

2021-02-28 20:09 UTC, tmible commented on ozon/src/index.html
> +  <script src="js/handlebars.js"></script>
Ой, ой, ой, не, не, не, нам такие гигантские файлы с внешним кодом в репозитории не нужны. Поставь через npm. [Вот же у них инструкция есть](https://handlebarsjs.com/installation/#npm-or-yarn-recommended)

2021-02-28 20:09 UTC, tmible commented on ozon/src/views/Common/Base.js
> +export class Base {
Чёт название класса абстрактное очень

2021-02-28 20:09 UTC, tmible commented on package.json
> +    "handlebars": "^4.7.7"
Так, стоп. А он что: и тут, и через `<script>` подключается? Один способ точно лишний.

2021-02-28 20:09 UTC, tmible commented on ozon/src/views/Common/Base.js
> +    render() { }
Так, обобщение получилось не очень. Либо это идея не очень. Попробуй передавать в конструкторе просто объект, в смысле без уточнения полей, и сохранять его в свойстве класса. Но это потеря значений по умолчанию для каждого поля конкретно (либо вообще все возможные поля дочерних классов можно перечислить). С методом `render()` примерно то же самое. Каждый дочерний класс сам себе строку, которую компилировать надо, в конструкторе ставит. Тогда можно `render()` дочерним вообще не писать: получается шаблонный метод.

2021-02-28 20:23 UTC, tmible commented
> Просто на данном этапе не особо понимаю что ок, а что не ок, опыта в вебе 0
Сейчас ок, потому что нет ничего, кроме этих элементов. Можно их просто через удобные классы скомпилировать и подставить через `innerHTML`. Но потом вот прикинь: разметка разрастётся, и придётся как-то подставлять эти отдельные строчки в общий макет страницы. Конечно, если вы найдёте способ норм это делать и сохранить вот эти классы, я только за.

> И про "Такие мелочи просто пишутся один раз в файле с разметкой и всё", вроде задача разработать SPA, то есть всё должно создаваться прямо в самом JS (если можно поясни плз как-то этот момент насчёт файла с вёрсткой).
Вот ты вызываешь метод `Handlebars.compile()` и передаёшь в него строчку. Пока норм, потому что она маленькая. Но, опять же, всё упирается в вёрстку и разрастание разметки из-за неё. Тогда уже просто так строку туда не передашь: слишком большая будет. Для этого шаблонизатору пишут в отдельном файле разметку (html, расширенный конструкциями шаблонизатора типа подстановки параметров, ветвления, циклов), а в js вызывают метод, компилирующий этот шаблон в разметку в соответствии с переданными значениями. Во-первых, шаблонизатор делает это всё через js всё равно, так что формально html там появляется только там же, где и у вас сейчас: в самом конце. Во-вторых, это всё ещё SPA, потому что для получаения другой странички не надо отправлять новый запрос и перезагружать страницу. Достаточно просто так же, как у вас сейчас, очистить корневой элемент DOM, скомпилировать шаблон запрашиваемой странички и подставить туда. Суть SPA не в том, чтобы не использовать html.

2021-03-01 16:56 UTC, lev4rT commented on ozon/src/index.html
> +  <script src="js/handlebars.js"></script>
Эту инструкцию я видел и такое ощущение, что она для бэкэнда (думаю, так и есть). Ибо далее она предполагает использование `require`, которой в браузере нет. Да, там есть и отдельная инструкция для браузера, но там надо вроде как ставить какие-то костыли. И вообще такое ощущение сложилось, будто этот `Handlebars` изначально подразумевался для шаблонизации на бэкенде, а для фронта какие-то костыли необходимы...

И насчёт того файлика: не знаю насколько это используется в работе, но на 1 семестре ТП мы все файлки так же переносили в отдельную папку. Проблема в том, что я не могу напрямую подключить файлы из `npm_modules`, т.к. у браузера нет доступа к ним.

2021-03-01 16:57 UTC, lev4rT commented
Решил убрать базовый класс, как и метод `render`. Вместо этого всё рендерится в одной строке, в которой присутствует итерация и ветвление, так должно быть гораздо лучше.

2021-03-02 07:42 UTC, tmible requested changes

2021-03-02 07:42 UTC, tmible commented on ozon/src/index.html
> +<!--  <script src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.12/handlebars.min.js"></script>-->
Окей, пускай пока остаётся, но потом, чтобы убрали!
Из репозитория выпиливай. Получайте по сети

2021-03-02 07:42 UTC, tmible commented on ozon/src/views/SignupPage/SignupPage.js
> +            '</form>'
Для этого есть третий тип кавычек в js — ``. Внутри них можно делать перенос строки

2021-03-02 07:42 UTC, tmible commented on ozon/src/views/SignupPage/SignupPage.js
> +            '</form>'
И, кстати, используйте одинаковый стиль кавычек. Везде, вроде, `'`, а в импортах `"`

2021-03-02 14:55 UTC, lev4rT commented
Сегодня плотно засел и разобрался более-менее. Насколько я понял, для корректной работы необходимо было подключить `Webpack`. Вынес шаблон в отдельный файл `.hbs`. Сейчас должно выглядеть приемлемо.

2021-03-02 18:43 UTC, tmible requested changes
Оооооо, webpack. Моё увожение. Думал уж придётся пойти на костыль, пока вебпака нет

2021-03-02 18:43 UTC, tmible commented on ozon/src/views/SignupPage/ifEquals.js
> +export default function(arg1, arg2, options) {
Это можно вынести, наверное, повыше. В utils какой-нибудь, типа того. В смысле выглядит так, как будто понадобится где-то ещё.

2021-03-02 18:43 UTC, tmible commented on package.json
> +    "start": "./node_modules/.bin/webpack --watch & node --experimental-modules ozon/server/index.mjs"
Сделай лучше два тогда. Один для прода: типо просто запуск. А второй для дева: с `--watch`.
Кстати, зачем `--experimental-modules` Актуальная версия ноды должна уже без этого работать.
И вместо обращения к бинарнику вебпака напрямую используй его cli

2021-03-02 23:35 UTC, lev4rT commented on package.json
> +    "start": "./node_modules/.bin/webpack --watch & node --experimental-modules ozon/server/index.mjs"
Согласен, что это выглядит странно, но без этого ключа мне выдаётся вот это:

![alt text](https://sun9-63.userapi.com/impf/UGdxML5PBxHQ8kKKT40RXZuigJuyBzR8R-jN2A/wlCA6TiQvAM.jpg?size=855x512&quality=96&sign=6933b7b869255e0afaf303d0be7d54dd&type=album)

Ubuntu довольно свежая, npm тоже, хз в чём проблема. С помощью гуглинга нашёл решение проблемы

2021-03-03 06:40 UTC, tmible commented on package.json
> +    "start": "./node_modules/.bin/webpack --watch & node --experimental-modules ozon/server/index.mjs"
А `node -v` что говорит?

2021-03-03 12:07 UTC, lev4rT commented on package.json
> +    "start": "./node_modules/.bin/webpack --watch & node --experimental-modules ozon/server/index.mjs"
v10.19.0

2021-03-03 12:22 UTC, tmible commented on package.json
> +    "start": "./node_modules/.bin/webpack --watch & node --experimental-modules ozon/server/index.mjs"
Так это ж старая пипец. Обновись, и всё будет без флагов работать

2021-03-03 19:13 UTC, lev4rT commented
Ноду обновил. Команды скриптов поменял на нормальные

2021-03-04 19:15 UTC, tmible requested changes

2021-03-04 19:15 UTC, tmible commented on ozon/src/views/SignupPage/SignupPage.js
> +import SignupT from "./SignupPage.hbs"
Название непонятное

2021-03-04 19:15 UTC, tmible commented on package.json
> +    "start": "webpack-cli & node ozon/server/index.js",
Почему `&`, мб `&&`?

2021-03-04 19:15 UTC, tmible commented on package.json
> +    "start": "webpack-cli & node ozon/server/index.js",
Тебя постфикс `-cli` не бесит?) Меня бесит. Но в целом пофигу. Можете оставить

2021-03-04 20:45 UTC, tmible approved these changes

2021-03-04 20:46 UTC, merged