Ozon 64 service worker
frontend-park-mail-ru/2021_1_DuckLuck pull request #30
Opened 2021-04-11 15:27 UTC by lev4rT

Прикрутил сервис воркера. Но есть вопрос насчёт проверки онлайна пользователя.
поле `navigator.onLine` работает ооочень странно. Она может показывать false, когда я онлайн. Или форсировать выход в онлайн. В общем порой живёт своей жизнью. В связи с чем вопрос как бы лучше проверять на онлайн пользователя

2021-04-11 18:58 UTC, DuckLuckBreakout commented on package.json
> -    "build": "webpack",
Вот тут убил сборку

2021-04-12 16:02 UTC, tmible requested changes

2021-04-12 16:02 UTC, tmible commented on ozon/server/index.js
> +const express = require('express');
Кстати, пора уже на `import` переехать

2021-04-12 16:02 UTC, tmible commented on ozon/src/utils/urls/urls.js
> +export const fileServerHost = 'http://localhost:8100';
Забыл?

2021-04-12 16:02 UTC, tmible commented on ozon/src/views/OfflineView/OfflineView.js
> + * @classdesc Class for signup page
🙂

2021-04-12 16:02 UTC, tmible commented on ozon/src/main.js
> +window.addEventListener('offline', () => console.warn('came offline'));
Ну, это дебаг какой-то

2021-04-12 16:06 UTC, tmible commented
Чёт много одного и того же в разных местах. Попробуй, чтобы сервис воркер в одном месте это сохранял всё. И только гет-запросы, конечно. Чтобы таким мидлваром был

2021-04-13 17:07 UTC, tmible requested changes

2021-04-13 17:07 UTC, tmible commented on ozon/src/index.html
>  </head>
Воу-воу-воу

2021-04-13 17:07 UTC, tmible commented on ozon/src/index.html
>  </body>
Я чего-то не понял или это двойной закрывающий тег?

2021-04-13 17:07 UTC, tmible commented on ozon/src/main.js
> +        }).catch((registrationError) => {
Мб тогда просто `.catch()`? В `.then()` же не нужно ничего делать?

2021-04-13 17:07 UTC, tmible commented on webpack.config.js
> +            {
Почему перенёс? Было норм

2021-04-14 10:34 UTC, tmible approved these changes

2021-04-14 10:34 UTC, merged