OZON-6 Add hbs and styles for login page
frontend-park-mail-ru/2021_1_DuckLuck pull request #4
Opened 2021-03-05 14:59 UTC by DuckLuckBreakout

2021-03-05 22:08 UTC, tmible requested changes

2021-03-05 22:08 UTC, tmible commented on ozon/src/views/Common/Button/Button.js
> +            parent
Господи, это точно всё нужно?

2021-03-05 22:08 UTC, tmible commented on ozon/src/views/Common/Link/Link.css
> +}
Это что?

2021-03-05 22:08 UTC, tmible commented on ozon/src/views/Common/Link/Link.js
> +            type,
Господи, и это всё нужно?

2021-03-05 22:08 UTC, tmible commented on ozon/src/views/LoginPage/LoginPage.hbs
> +        <label for="password">
А если не будет такого?
Мб внести факт необходимости наличия `label` в класс `Input`?

2021-03-05 22:08 UTC, tmible commented on ozon/src/views/LoginPage/LoginPage.js
> +        const div = document.createElement('div');
Чё за схема лютая?) Шаблонизатор же есть

2021-03-06 16:47 UTC, tmible requested changes

2021-03-06 16:47 UTC, tmible commented on ozon/src/views/Common/Button/Button.js
> +            name,
Ну хз, ну чёт многовато строк. У вас есть кодстайл в команде?

2021-03-06 16:47 UTC, tmible commented on ozon/src/views/Common/Link/Link.css
> +
Ну тоже про кодстайл

2021-03-06 16:47 UTC, tmible commented on ozon/src/views/Common/Link/Link.js
> +            href,
То же самое

2021-03-06 16:47 UTC, tmible commented on ozon/src/views/LoginPage/LoginPage.js
> +        return html;
Чёт извращения какие-то тут с 25-й строки по 35-ю. Объясни, что это и почему так?

2021-03-06 16:57 UTC, DuckLuckBreakout commented on ozon/src/views/LoginPage/LoginPage.js
> +        return html;
Выглядит оно очень страшно, да
`LoginPage.render()` должен возвращать только сам блок авторизации, но при этом надо еще и добавить блок, который перекроет собой старые компоненты страницы. Какой-то более менее нормальный вариант добавить этот блок я не смог придумать, в связи с чем родился вот этот ужас

2021-03-06 18:26 UTC, tmible commented on ozon/src/views/LoginPage/LoginPage.js
> +        return html;
Это можно сделать проще и красивее с помощью css и без лишних элементов

2021-03-07 18:10 UTC, tmible requested changes

2021-03-07 18:10 UTC, tmible commented on ozon/src/views/SignupPage/SignupPage.css
> +}
Тут с логином не одинаковые стили? Мб что-нибудь как-нибудь объединить?

Кстати, очень советую для z-index использовать переменные. Вы в них рано или поздно запутаетесь, а если создать константы, окажется, что нужно всего там около 5. Ну и так вообще они очень удобные

2021-03-07 18:10 UTC, tmible commented on ozon/src/views/SignupPage/SignupPage.hbs
> +</div>
Да и шаблоны у них тоже очень похожие. Мб их общую часть тоже как-нибудь вынести? Я думаю, blind этот ещё может понадобиться

2021-03-07 18:10 UTC, tmible commented on ozon/src/views/LoginPage/LoginPage.js
> +        return new DOMParser().parseFromString(template, 'text/html').getElementById('login-block-wrapper');
Вот этот `DOMParser` меня напрягает, конечно. Я пропустил: как раньше без него обходились?

2021-03-07 18:43 UTC, tmible commented on ozon/src/views/SignupPage/SignupPage.js
> +import LoginTemplate from "../LoginPage/LoginPage.hbs";
Лишний импорт, кстати

2021-03-07 23:20 UTC, DuckLuckBreakout commented
Страницы авторизации и регистрации теперь имеют общие стили и шаблон
Выделил отдельно объекты `popup`, `blind`

2021-03-07 23:49 UTC, tmible requested changes
Проверь за одно по возможности всякие консол логи, комментарии, не нужные импорты и т.д.

2021-03-07 23:49 UTC, tmible commented on ozon/src/views/Common/AuthenticationForm/AuthenticationForm.js
> +    constructor({} = {}) {
Стоп, зачем?

2021-03-08 08:31 UTC, DuckLuckBreakout commented on ozon/src/views/Common/AuthenticationForm/AuthenticationForm.js
> +    constructor({} = {}) {
Это я делал копипаст из другой сущности, удалил все атрибуты, думал, что позже добавлю, в итоге добавлять было нечего, а я забыл подтереть
Аналогично было в конструкторе `blind`

2021-03-08 08:49 UTC, tmible approved these changes

2021-03-08 08:50 UTC, merged