Ozon 73 front pre defense fix
frontend-park-mail-ru/2021_1_DuckLuck pull request #40
Opened 2021-04-16 12:06 UTC by DuckLuckBreakout

В данную ветку сливаю все изменения, который делаются перед предзащитой

2021-04-16 21:15 UTC, Tullerpeton commented on ozon/src/utils/urls/urls.js
> +export const serverHost = 'http://localhost:8080';
Урлы забыл

2021-04-19 19:15 UTC, tmible requested changes

2021-04-19 19:15 UTC, tmible commented on ozon/src/views/ProductsView/ProductsView.css
> +    /*margin: auto;*/
Не нужно?

2021-04-19 19:15 UTC, tmible commented on ozon/src/models/OrderModel.js
> +                ).then((parsedJson) => {
Жесть я тут в коде запутался. Разнеси все скобочки и точки, чтобы хорошо было

2021-04-19 19:15 UTC, tmible commented on ozon/src/models/OrderModel.js
> +                this.bus.emit(Events.OrderLoaded, Responses.Success);
Точно поведение ничем не отличается? Кстати, `err` не нужен

2021-04-19 19:15 UTC, tmible commented on ozon/src/views/SignupView/SignupView.js
> +            inputs[2].placeholder = 'Повтор пароля';
Почему не сделать это в разметке? И в логине тоже

2021-04-19 19:15 UTC, tmible commented on ozon/src/models/CartModel.js
> +                    -this.#products[this.#products.indexOf(product)].count);
А на 115-й строке пришлось diff считать. Мб к одному интерфейсу эти события привести?

2021-04-21 11:12 UTC, lev4rT commented on ozon/src/models/OrderModel.js
> +                this.bus.emit(Events.OrderLoaded, Responses.Success);
В случае ошибки просто не подставим адрес, но все остальные данные для заказа будут загружены

2021-04-21 11:14 UTC, lev4rT commented on ozon/src/views/SignupView/SignupView.js
> +            inputs[2].placeholder = 'Повтор пароля';
Из-за оставшегося срендеренного кэша

2021-04-21 11:43 UTC, tmible approved these changes

2021-04-21 11:55 UTC, merged