New version of validator
frontend-park-mail-ru/2021_1_DuckLuck pull request #45
Opened 2021-04-24 16:26 UTC by lev4rT

Подумал, что можно сделать валидатор ещё лучше, возвращая не просто булевское условие валидности, а стркутуру в которой содержатся поля, которые невалидны, дабы пользователь лучше понимал где ошибка

2021-04-25 15:00 UTC, tmible requested changes

2021-04-25 15:00 UTC, tmible commented on ozon/src/views/BaseView.js
> +                if (invalidFields.includes(fields.firstName)) {
А если пробегаться по `invalidFields`, можно это всё в пару строк упаковать

2021-04-25 15:00 UTC, tmible commented on ozon/src/presenters/ProfilePresenter.js
> +     * @return {Object} contains array of invalid fields
Не так же

2021-04-25 15:00 UTC, tmible commented on ozon/src/presenters/ProfilePresenter.js
> +        form.appendChild(input);
Так. Не понял, зачем эта хитрая процедура

2021-04-25 15:00 UTC, tmible commented on ozon/src/modules/Valiadtor/validator.js
> +    const isValidName = /^[a-zA-Zа-яА-Я]{3,30}$/.test(input.value);
Ян, получается, не сможет зарегистрироваться? Или кореец с фамилией "О")0)0

2021-04-25 15:00 UTC, tmible commented on ozon/src/models/LoginModel.js
> +                throw null;
Вот тут не понял, почему так. Норм же было

2021-04-26 09:37 UTC, lev4rT commented on ozon/src/presenters/ProfilePresenter.js
> +        form.appendChild(input);
Функция валидатора принимает форму, в которой пробегается по всем полям и смотрит, валидны ли они. Но вообще я так подумал, что лучше кидать сразу инпуты туда

2021-04-26 09:45 UTC, lev4rT commented on ozon/src/models/LoginModel.js
> +                throw null;
Подумал, что дублировать не нужно, когда у нас тот же самый код в catch-блоке

2021-04-26 17:09 UTC, tmible commented on ozon/src/utils/validationFields/validationFields.js
> +export const fieldsPlaceholders = {
Это же не плейсхолдеры

2021-04-26 17:09 UTC, tmible commented on ozon/src/models/LoginModel.js
> +                throw null;
Ну тогда хотя бы строку какую с сообщением бросал

2021-04-26 17:11 UTC, tmible commented on ozon/src/presenters/ProfilePresenter.js
> +        form.appendChild(input);
Это я понял. Я не понял, зачем создавать новые элементы. Те, что уже существуют нельзя использовать?

2021-05-01 11:15 UTC, tmible approved these changes

2021-05-01 11:15 UTC, merged