Ozon 79 cart counter fix
frontend-park-mail-ru/2021_1_DuckLuck pull request #46
Opened 2021-04-24 20:47 UTC by lev4rT

Пофиксил каунтер. Избавился от глупой логики ожидания ответов от корзины

2021-04-25 15:09 UTC, tmible requested changes

2021-04-25 15:09 UTC, tmible commented on ozon/src/presenters/LoginPresenter.js
> +            Bus.globalBus.emit(Events.CartAddLastProduct);
Это зачем так?

2021-04-26 08:53 UTC, lev4rT commented on ozon/src/presenters/LoginPresenter.js
> +            Bus.globalBus.emit(Events.CartAddLastProduct);
Из-за ситуации, когда пользоветль жмёт на доавить товар в корзину, но он не залогинен. Он логинется и тот товар, на который он кликал - попадает в корзину. Если он не кликал на добавление товара до логина - никакой товар добавляться не будет

2021-04-26 20:01 UTC, tmible approved these changes

2021-04-26 20:01 UTC, merged