Ozon 86 search
frontend-park-mail-ru/2021_1_DuckLuck pull request #47
Opened 2021-04-26 08:51 UTC by lev4rT

2021-04-26 09:46 UTC, DuckLuckBreakout commented on ozon/src/utils/urls/urls.js
> +export const serverHost = 'http://localhost:8080';
:(

2021-04-26 10:11 UTC, DuckLuckBreakout commented on .github/workflows/s3.yml
> +      - name: Check urls
Все, теперь роняю билд, если опять локалхост

2021-04-26 20:07 UTC, tmible requested changes

2021-04-26 20:07 UTC, tmible commented on ozon/src/main.js
> +    .register(/^\/search\/(?<page>[0-9]*)\/\?text=(?<searchText>[А-Яа-яA-Za-z0-9\s]*)$/, productsPresenter.view)
Ну параметр-то, можно не регистрировать

2021-04-26 20:07 UTC, tmible commented on ozon/src/views/ProductsView/ProductsView.js
> +    types = {
Нет смысла в каждом экземпляре хранить копию. Либо в статическое поле выноси, либо в константу там

2021-05-01 14:03 UTC, lev4rT commented
Попытался научуить роутер работать с URL-параметрами. Основная проблема в том, что если вбивать запрос с браузера - то параметры сразу парсятся в `window.location.search`, но если вбивать поиск в форму, то есть работать сразу через фукцию Router.open, то в `window.location.search` ничего не парсится и приходится что-то выдумывать. Мб есть решение как получше сделать вот эту возню с параметрами в запросе?

2021-05-01 20:59 UTC, tmible requested changes
Можно в начале брать объектик из аргументов, если `window.location.search` не пустой, докидывать параметры из него в объект (тут надо подумать, можно ли портить оригинальный объект, переданный через аргументы метода), а потом вызывать `view.show()`, передавая ему этот объект, если он не пустой. Итого 1 строка с `window.location.search`, 1, если не портить входной объект и ифчик в конце на вызов `view.show()` -- вроде, то, что нужно.
P.S. Можно изменить логику аргумента `URLParams`, и тогда ифчик в конце не понадобится

2021-05-01 20:59 UTC, tmible commented on ozon/src/main.js
> +    .register(/^\/search\/(?<page>[0-9]*)\/?$/, productsPresenter.view)
И вопросик тоже убирай

2021-05-01 20:59 UTC, tmible commented on ozon/src/utils/router/Router.js
> +            path = path.substr(0, path.length - 1);
Так, а если его нет?

2021-05-01 20:59 UTC, tmible commented on ozon/src/views/ProductsView/ProductsView.js
> +                    Router.open(`/search/${page}/?text=${this.IDs['searchText']}`);
Так, то объектом, то строкой

2021-05-02 15:40 UTC, lev4rT commented on ozon/src/utils/router/Router.js
> +            path = path.substr(0, path.length - 1);
Не быть его не может, так как выше есть проверка на то, что есть хотя бы один параметр в запросе, то есть `&` поставится в любом случае. Если же параметров нет - то мы просто сразу же выйдем из функции (кстати, избавился от излишней вложенности в функции `adaptPath` роутера)

2021-05-02 15:42 UTC, lev4rT commented on ozon/src/views/ProductsView/ProductsView.js
> +                    Router.open(`/search/${page}/?text=${this.IDs['searchText']}`);
кидать во второй объект какие-то параметры в роутер - это уже пережиток прошлого, когда не было групп в регулярках. Там пока только replaceView находится, но не исключено, что что-то ещё поребуется в будущем

2021-05-02 16:30 UTC, tmible commented on ozon/src/utils/router/Router.js
>          path = this.adaptPath(path, pathParams);
Стоп, нет. Получается, сначала объект в строку переводится

2021-05-02 16:30 UTC, tmible commented on ozon/src/utils/router/Router.js
> +        Object.assign(pathParams, this.parseSearch(window.location.search));
А потом обратно

2021-05-02 16:30 UTC, tmible commented on ozon/src/views/ProductsView/ProductsView.js
> +                    Router.open(`/search/${page}/?text=${this.IDs['searchText']}`);
В любом случае надо каким-то одним способом передавать

2021-05-02 16:34 UTC, tmible commented on ozon/src/views/ProductsView/ProductsView.js
> +                    Router.open(`/search/${page}/?text=${this.IDs['searchText']}`);
Можно передавать пустой просто объект, как и по умолчанию. Если этот варик не нравится, заверни их в декомпозицию -- получится что-то типа именованных параметров, как в питоне. Ну или просто строкой, но так как вью в итоге объект нужен, я за передачу сразу объектом

2021-05-02 16:44 UTC, tmible commented on ozon/src/utils/router/Router.js
> +        path = path.substr(0, path.length - 1);
Моя ошибочка тут. Понял задумку. Чтобы не удалять последний `&` есть метод `join()` :)

2021-05-02 21:45 UTC, tmible approved these changes

2021-05-02 21:45 UTC, tmible commented on ozon/src/utils/router/Router.js
> +        path += '?' + Object.keys(params).map((key) => [key, params[key]].join('=')).join('&');
Вот это класс. Вот это лайк

2021-05-02 21:46 UTC, merged