Ozon 8 profile page
frontend-park-mail-ru/2021_1_DuckLuck pull request #5
Opened 2021-03-06 23:49 UTC by lev4rT

Запуск: npm start
### **Для того, чтобы можно было потыкать страничку профиля - нужно предварительно авторизоваться. Тестовый аккаунт:**

test@mail.ru
qweasd

P.S. На сервер можно не смотреть. Пока что это просто заглушка с лекции с авторизацией, тестовым аккаунтом и куками

2021-03-07 10:24 UTC, lev4rT commented
Изменения в дизайне.

2021-03-07 18:34 UTC, tmible requested changes

2021-03-07 18:34 UTC, tmible commented on ozon/src/main.js
> +            url: 'http://localhost:7777/api/v1/user/signup',
Вот хост (точнее даже всё вплоть до `/user/signup`) отсюда лучше вынести и сделать константой в модуле, отвечающим непосредственно за работу с сетью. Ну и, вынести, получается все запросы отсюда в тот модуль. Таким образом получается тут просто вызов метода одного модуля, а в нём уже вызов postUsingFetch с нужными параметрами

2021-03-07 18:34 UTC, tmible commented on ozon/src/main.js
>                      console.log(error);
Ой, ой, ой, проглядел. Везде потри логи, пожалуйста

2021-03-07 18:34 UTC, tmible commented on ozon/src/views/Common/Img/Img.css
> +}
Пс, `object-fit` погуглите, обязательно используйте и понтанитесь им на РК!

2021-03-07 18:34 UTC, tmible commented on ozon/src/views/ProfilePage/ProfilePage.js
> +        lastNameInput.placeholder = lastName;
Да можно тогда в переменную их и не сохранять, раз только один раз нужны

2021-03-07 18:34 UTC, tmible commented on ozon/src/views/ProfilePage/ProfilePage.js
> +import SignupTemplate from "../SignupPage/SignupPage.hbs";
Чёт тут половина ненужные, не?

2021-03-07 18:34 UTC, tmible commented on ozon/src/views/ProfilePage/ProfilePage.js
> +        const page = document.createElement('div');
Так, это чтобы без `DOMParser`, как в 4-м ПР?

2021-03-07 18:34 UTC, tmible commented on ozon/src/views/ProfilePage/ProfilePage.hbs
> +            <div class="profile-info__user_firstname">Nikita Suvorov</div>
Понял

2021-03-07 18:34 UTC, tmible commented on ozon/src/views/ProfilePage/ProfilePage.css
> +    /* identical to box height */
Можно тогда в переменную вынести

Ну и цвета, всякие тоже можно. Но их уже в глобальные константы. В общем, разберёшься.

2021-03-07 18:49 UTC, tmible commented on ozon/src/main.js
> +            url: 'http://localhost:7777/api/v1/user/signup',
Хотя, наверное, учитывая сроки, можно пока от этого нового модуля отказаться. Короче, адрес бэка -- в константу, остальное по возможности

2021-03-08 09:53 UTC, tmible commented on ozon/src/main.js
>                      console.log(error);
Опс, извините, тупанул. Тут можно и нужно оставить. Можно даже `consol.error()`, чтобы понятнее было, но необязательно

2021-03-08 09:54 UTC, tmible commented on ozon/src/views/ProfilePage/ProfilePage.css
> +    /* identical to box height */
Переменные в этоп ПР отменяются

2021-03-08 11:49 UTC, tmible approved these changes

2021-03-08 13:01 UTC, merged