Ozon 100 review form
frontend-park-mail-ru/2021_1_DuckLuck pull request #51
Opened 2021-05-01 18:45 UTC by lev4rT

2021-05-01 19:00 UTC, DuckLuckBreakout commented
Добавили форму для написания отзыва к товару.
На данный момент не реализовано только прикрепления фотографий.
CSS'у тут не очень хорошо, он в первичной версии. Например, присутствует:
```css
.bold {
    font-weight: var(--bold-font);
}
```
Подобному тут явно не место, оно уйдет, когда будем адаптировать css, заодно его разгребая

2021-05-01 21:02 UTC, tmible commented
> Подобному тут явно не место, оно уйдет, когда будем адаптировать css, заодно его разгребая

Почему нет? Выглядит хорошо. Весь бутстрап на таких классах держится

2021-05-01 21:08 UTC, DuckLuckBreakout commented
> > Подобному тут явно не место, оно уйдет, когда будем адаптировать css, заодно его разгребая
> 
> Почему нет? Выглядит хорошо. Весь бутстрап на таких классах держится

Я имею в виду, что это настолько универсальный модификатор, что ему не место только в этой вьюхе
Планирую вынесу его куда-то выше, но не сейчас

2021-05-01 21:31 UTC, tmible requested changes

2021-05-01 21:31 UTC, tmible commented on ozon/src/main.js
> +import {ReviewView} from './views/ReviewView/ReviewView';
Так, почему по-разному?

2021-05-01 21:31 UTC, tmible commented on ozon/src/models/ReviewModel.js
> +                body: null,
Естественно, null

2021-05-01 21:31 UTC, tmible commented on ozon/src/models/ReviewModel.js
> +                    url: `${serverApiPath}${urls.productUrl}/${this.product.id}`,
А передаётся объект, содержащий только id? Почему тогда не просто переменная?

2021-05-01 21:31 UTC, tmible commented on ozon/src/views/ProductView/ProductView.hbs
> +                        <span class="{{productStyles.buttonText}}">В корзину</span>
Почему это вернулось? Какие-то конфликты не так порешали?

2021-05-01 21:31 UTC, tmible commented on ozon/src/views/ProductView/ProductView.hbs
> +                <span class="">Оставить отзыв</span>
Какой класс?

2021-05-01 21:31 UTC, tmible commented on ozon/src/utils/urls/urls.js
> +    productReviews: '/review/product',
Стоп, это разные вещи?

2021-05-01 21:31 UTC, tmible commented on ozon/src/views/ReviewView/ReviewView.js
> +        this.bus.emit(Events.ReviewLoad);
И там происходит куча сетевых запросов, чтобы узнать то, что и так уже известно? Название товара, id и имя пользователя? Мб их как-то передать сюда просто?

2021-05-01 21:31 UTC, tmible commented on ozon/src/views/ReviewView/ReviewView.js
> +                }
Ну тут прям бог велел это хотя бы в  один цикл уместить. А так даже и в одну строку можно

2021-05-01 21:31 UTC, tmible commented on ozon/src/views/ReviewView/ReviewView.js
> +                }
Тут аналогично

2021-05-01 21:31 UTC, tmible commented on ozon/src/utils/urls/urls.js
> +    reviewRights: '/review/rights/product/',
Так, а это что?

2021-05-01 21:31 UTC, tmible commented
> > > Подобному тут явно не место, оно уйдет, когда будем адаптировать css, заодно его разгребая
> > 
> > 
> > Почему нет? Выглядит хорошо. Весь бутстрап на таких классах держится
> 
> Я имею в виду, что это настолько универсальный модификатор, что ему не место только в этой вьюхе
> Планирую вынести его куда-то выше, но не сейчас

А, тогда да, согласен

2021-05-02 13:21 UTC, lev4rT commented on ozon/src/models/ReviewModel.js
> +                    url: `${serverApiPath}${urls.productUrl}/${this.product.id}`,
Не совсем, далее этот объект будет заполнен всеми остальными необходимыми полями
```
this.product = {
                        id: response.id,
                        category: response.category,
                        image: `${staticServerHost}${response.images[0]}`,
                        title: response.title,
                        href: `/item/${this.product.id}`,
                    };
```

2021-05-02 13:27 UTC, lev4rT commented on ozon/src/views/ProductView/ProductView.hbs
> +                        <span class="{{productStyles.buttonText}}">В корзину</span>
Есть подозрения, что ветка была отнаследована от старой версии дева. Наверно, Ваня забыла запулить дев перед созданием новой ветки. Смержил с девом текущую ветку

2021-05-02 13:31 UTC, lev4rT commented on ozon/src/views/ReviewView/ReviewView.js
> +        this.bus.emit(Events.ReviewLoad);
Тут из названия не совсем очевидно, но главная задача эмитации этого события - это проверка на то, имеет ли пользователь возможность написать сам отзыв. То есть проверка на то покупал ли он товар до этого. А все остальные параметры, в принципе, можно и вправду получить из остальных моделей

2021-05-02 14:59 UTC, lev4rT commented on ozon/src/models/ReviewModel.js
> +                    url: `${serverApiPath}${urls.productUrl}/${this.product.id}`,
Более не нуждается в рассмотрении. Теперь все данные берутся из соответствующих моделей

2021-05-02 16:59 UTC, tmible requested changes
Кое-что ещё из прошлого ревью не отметил resolved

2021-05-02 16:59 UTC, tmible commented on ozon/src/models/ProfileModel.js
> +    getProfileData(noRender = false) {
Нет, модель за это отвечать не должна. Этот ифчик можно оставить в презентере. Он же как раз по пути между моделью и вью стоит

2021-05-02 16:59 UTC, tmible commented on ozon/src/views/ReviewView/ReviewView.js
>                      stars[i].setAttribute('src', emptyStarLink);
`i < this.presenter.rating ? starLink : emptyStarLink`
Ну и заодно это тут оставлю:
`stars.forEach((star, i) => star.setAttribute('src', i < this.presenter.rating ? starLink : emptyStarLink))`

2021-05-02 18:25 UTC, lev4rT commented on ozon/src/models/ProfileModel.js
> +    getProfileData(noRender = false) {
Тогда не совсем понятно как давать понять презентеру, что не надо рисовать, если не передавать в метод какую-то инфу. Можно ли при эмитации события по шине помимо параметра успеха\неуспеха получения данных с сервера передавать параметр, который отвечает за то, нужно ли рисовать данные? Но тогда получается эта переменная в данном методе все равно сохранится...

2021-05-02 18:36 UTC, lev4rT commented
Насчёт того, что пофиксил не все ишьюсы - сорян, моя вина, надо было переключится на другую ветку в процессе, `git stash` сделал, а когда вернулся - попнуть изменения забыл

2021-05-02 22:01 UTC, tmible commented
В `urls` два одинаковых пути. Вроде, убирал их. Короче, глянь

2021-05-02 22:02 UTC, tmible commented on ozon/src/models/ProfileModel.js
> +    getProfileData(noRender = false) {
Так, я сейчас посмотрел код и вообще не увидел необходимости трогать модель и вью: на событие подписан презентер, он возвращает просто по гетерам данные из модели

2021-05-03 10:48 UTC, lev4rT commented
Вроде давно уже убрал дубликаты урла. Теперь для ревью только два урла:
```
review: '/review/product',
reviewRights: '/review/rights/product/',
```

2021-05-03 12:44 UTC, tmible commented on ozon/src/presenters/ProfilePresenter.js
> +        this.model.getProfileData(true);
А, стоп. Так проблема в том, что это в конструкторе. Получается, если пользователь первый раз откроет сайт, отправятся запросы за его профилем. Нужно просто, чтобы презентер реагировал на событие запроса данных профиля, выдавая, что сейчас в модели есть. Если ничего нет -- значит, не залогинен. Ничего, кроме, кучки гетов ради этого события делать не нужно

2021-05-03 14:06 UTC, lev4rT commented on ozon/src/presenters/ProfilePresenter.js
> +        this.model.getProfileData(true);
Проблема в том, что данные могут быть не прогружены и оно вернёт undefined, хотя сами данные в базе лежать и прогрузятая позже, т.к промисы. Есть идея сделать вызов события прогрузки данных с профиля когда промис завершится и подписать на это событие замену значений в инпутах вьюхи ревью

2021-05-03 16:02 UTC, tmible commented on ozon/src/presenters/ProfilePresenter.js
> +        this.model.getProfileData(true);
Согласен: неприятный момент. Но я пока не вижу такого сценария. Либо пользователь уже залогинен, и в ответ на логин пришли его данные, либо незалогинен и тогда права на ревью ответят не ок.
По-хорошему, конечно надо использовать какую-нибудь обёртку, обозначающую изменяемый объект, но писать её самому -- такое (хотя можно, конечно), а фреймворки нельзя. Так что в текущих условиях, думаю, норм положиться на вышеизложенные соображения

2021-05-03 16:53 UTC, lev4rT commented
Вынес гет данных профиля из конструктора.

> Либо пользователь уже залогинен, и в ответ на логин пришли его данные

Если пользователь логинится (в форме логина) или регестрируется, то тогда да, всё ок, данные сохранятся в модели, но если он после этого закроет сайт или нажмёт F5, то данных в моделе не будет. Мы не узнаем залогинен ли пользователь до первых его действий, для которых нужна регистрация, следовательно, никакие данные о нем также не знаем, в модели `undefined`.
В хедере есть проверка на то, залогинен ли пользователь, чтобы отрисовывать нужную надпись под иконкой. Добавил доп логику туда: если пользователь залогинен  - помимо замены текста под иконкой получаем данные о профиле. Таким образом, если пользователь не залогинен, то и никакие лишние запросы делаться не будут.

>   либо незалогинен и тогда права на ревью ответят не ок.
Да, тут все так, данные о пользователе в моделе вообще не нужны

2021-05-04 12:09 UTC, tmible commented
> Если пользователь логинится (в форме логина) или регестрируется, то тогда да, всё ок, данные сохранятся в модели, но если он после этого закроет сайт или нажмёт F5, то данных в моделе не будет. Мы не узнаем залогинен ли пользователь до первых его действий, для которых нужна регистрация, следовательно, никакие данные о нем также не знаем, в модели `undefined`.
> В хедере есть проверка на то, залогинен ли пользователь, чтобы отрисовывать нужную надпись под иконкой. Добавил доп логику туда: если пользователь залогинен - помимо замены текста под иконкой получаем данные о профиле. Таким образом, если пользователь не залогинен, то и никакие лишние запросы делаться не будут.

Ну, хедер -- это тоже не место для этого, конечно. Для борьбы с закрытиями/открытиями, новыми вкладками, F5, придумали `localStorage`

2021-05-04 18:37 UTC, tmible requested changes

2021-05-04 18:37 UTC, tmible commented on ozon/src/views/ProductView/ProductView.hbs
> +>>>>>>> develop
Кое-что упустили

2021-05-04 18:37 UTC, tmible commented on package.json
> +    "start-dev": "webpack --env=dev --watch & node --experimental-modules ozon/server/index.mjs",
Ну и это опять же

2021-05-04 20:00 UTC, lev4rT commented
Косяк был на моей стороне. По умолчанию надо ставится 10 версии. Обновил ноду

2021-05-04 20:24 UTC, tmible approved these changes

2021-05-04 20:24 UTC, merged