Ozon 110 products filtration
frontend-park-mail-ru/2021_1_DuckLuck pull request #55
Opened 2021-05-04 16:37 UTC by lev4rT

Добавил фильтрацию

2021-05-04 16:54 UTC, lev4rT commented
Сорян что так поздно. В середине дня при попытке переезда бэкенда на докер у меня полетела система ввиду отсутствия места. Переустановка системы заняло некоторое время.

2021-05-04 17:57 UTC, tmible requested changes

2021-05-04 17:57 UTC, tmible commented on ozon/src/views/ProductsView/ProductsView.js
> +        document.getElementById('max_price').value = filter.max_price != 9999999 ? filter.max_price: '';
Вместо `9999999` лучше использовать `undefined`

2021-05-04 17:57 UTC, tmible commented on ozon/src/views/ProductsView/ProductsView.js
> +            switch (this.#viewType) {
Это, наверное, стоит на тернарник заменить

2021-05-04 17:57 UTC, tmible commented on package.json
> +    "start-dev": "webpack --env=dev --watch & node --experimental-modules ozon/server/index.mjs",
`"type": "module"`?

2021-05-04 21:06 UTC, tmible commented on ozon/src/models/ProductsModel.js
> +            body.filter.max_price = body.filter.max_price === undefined ? 1e6: body.filter.max_price;
А, здесь бэк с `undefined` не умеет работать... Я имел в виду вообще абстрагироваться от чисел и, если нет `max_price`, то в запросе в базу просто не указывать верхнюю границу. А в jsonе, наверное, `null` слать, чтобы и бэк понял

2021-05-04 21:06 UTC, tmible commented on ozon/src/views/ProductsView/ProductsView.js
> +                    Router.open(`/search/${page}/`, {text: this.IDs['searchText']});
Этот `switch`, кстати, тоже можно сделать тернарником, если понравилось

2021-05-04 21:06 UTC, tmible commented on ozon/src/views/ProductsView/ProductsView.js
> +                    Router.open(`/search/${page}/`, {text: this.IDs['searchText']});
Кстати, так и должно быть? Я про изменение строки

2021-05-04 21:16 UTC, lev4rT commented on ozon/src/models/ProductsModel.js
> +            body.filter.max_price = body.filter.max_price === undefined ? 1e6: body.filter.max_price;
К сожалению, бэк пока не умеет работать вообще ни с какими значениями в max/min price полях, кроме числовых

2021-05-04 21:29 UTC, lev4rT commented on ozon/src/views/ProductsView/ProductsView.js
> +                    Router.open(`/search/${page}/`, {text: this.IDs['searchText']});
Упс, проглядел, спасибо

2021-05-05 08:22 UTC, tmible requested changes

2021-05-05 08:22 UTC, tmible commented on ozon/src/views/ProductsView/ProductsFilter.scss
> +}
Два раза один и тот же

2021-05-05 08:50 UTC, tmible approved these changes

2021-05-05 08:55 UTC, merged