Ozon 109 visible reviews on page
frontend-park-mail-ru/2021_1_DuckLuck pull request #57
Opened 2021-05-04 18:00 UTC by lev4rT

Были прикручены отзывы на странице товара

2021-05-04 20:25 UTC, tmible commented
@lev4rT @DuckLuckBreakout 
Конфликтики :)

2021-05-04 21:33 UTC, tmible requested changes

2021-05-04 21:33 UTC, tmible commented on ozon/src/presenters/ReviewPresenter.js
> +        switch (result) {
Ну зачем `switch`-то?

2021-05-04 21:33 UTC, tmible commented on ozon/src/views/Common/Pagination/Pagination.js
> +            value: 'Загрузить ещё',
Ооооо, вот это я понимаю пагинация 👍

2021-05-04 21:33 UTC, tmible commented on ozon/src/views/Common/Pagination/Pagination.js
> +            if (!this.pagesCount) {
Так, это что за недостижимый код? Всё в `if`, а в нём первой строкой `return`. Кстати, в eslint есть такое правило. Если правильно помню что-то вроде `no-unreachable-code`

2021-05-04 21:33 UTC, tmible commented on ozon/src/presenters/ProductPresenter.js
> +    #sortDirection;
Так, а зачем в презентере их хранить?

2021-05-04 21:33 UTC, tmible commented on ozon/src/views/ProductView/ProductView.js
> +        if (paginationInfo.pagesCount === paginationInfo.currentPage) {
Там нумерация точно так работает? Не потеряется последняя страница? Или наоборот: не пойдёт лишний запрос за несуществующей?

2021-05-04 21:33 UTC, tmible commented on ozon/src/views/ProductView/ProductView.js
> +            select: [
Кстати, по выставленной оценке бы ещё. Но это, думаю, знаете. Прямо сейчас не нужно, но вообще сделайте

2021-05-04 22:05 UTC, lev4rT commented on ozon/src/views/ProductView/ProductView.js
> +        if (paginationInfo.pagesCount === paginationInfo.currentPage) {
Тестировал, все норм было. Если страница последняя -кнопки "загрузить ещё" просто не будет, слеовательно запрос никак и не последует

2021-05-05 08:29 UTC, tmible approved these changes

2021-05-05 08:33 UTC, merged