Ozon 36 linter integration
frontend-park-mail-ru/2021_1_DuckLuck pull request #6
Opened 2021-03-07 16:31 UTC by lev4rT

Внедрил Линтер в проект. Сами файлы от ошибок не фиксил

## npm run lint

2021-03-07 18:36 UTC, tmible requested changes
Подключи ещё husky. Настойчиво рекомендую. Очень простая, но оочень полезная штука

2021-03-07 18:36 UTC, tmible commented on .eslintrc.json
> +    }
А что, нет?

2021-03-08 13:01 UTC, tmible requested changes

2021-03-08 13:01 UTC, tmible commented on ozon/src/views/Common/Input.js
> +        value = ''} = {}) {
Вот здесь для читаемости я бы `) {` перенёс на новую строку. Уточни в кодстайле и добавь в правила, если это по кодстайлу

2021-03-08 13:01 UTC, tmible commented on ozon/src/views/SignupPage/SignupPage.js
> +            new Input({type: 'email',
Тут тоже в кодстайле уточните, мб, стоит уже переносить на следующую строку с первого поля

2021-03-08 13:01 UTC, tmible commented on ozon/src/views/SignupPage/SignupPage.js
> +                placeholder: 'email'}),
И закрывающую скобку тогда тоже

2021-03-08 13:18 UTC, lev4rT commented
Я не уверен, что есть настолько точечные правила. В документации нагуглил только правила для массивов, но это не то.
https://eslint.org/docs/rules/array-bracket-newline
В любом случае конфиге указано, что использован кодстайл гугла, которому, думаю, можно доверять.

2021-03-08 13:22 UTC, tmible commented
Да, я имел в виду, что если в кодстайле нет, то сами решите

2021-03-08 13:35 UTC, tmible commented
> Я не уверен, что есть настолько точечные правила. В документации нагуглил только правила для массивов, но это не то.
> https://eslint.org/docs/rules/array-bracket-newline
> В любом случае конфиге указано, что использован кодстайл гугла, которому, думаю, можно доверять.

Вот, смотри: гугл в [своём кодстайле](https://google.github.io/styleguide/jsguide.html) всю дорогу используют
```
const obj = {
  lol: kek,
};
```

Вот тоже солидный [кодстайл airbnb](https://github.com/airbnb/javascript/issues/1380) про поводу длинных условий if

2021-03-08 17:37 UTC, lev4rT commented on ozon/src/views/Common/Input.js
> +        value = ''} = {}) {
18:5  error  Opening curly brace does not appear on the same line as controlling statement  brace-style

2021-03-08 17:50 UTC, tmible commented on ozon/src/views/Common/Input.js
> +        value = ''} = {}) {
Покажи, как перенёс?

2021-03-08 17:52 UTC, tmible requested changes

2021-03-08 17:52 UTC, tmible commented on ozon/src/views/SignupPage/SignupPage.js
> +            ),
Так, а круглую зачем переносить? Они как открывали вместе `({`, так пусть и закрывают `})`

2021-03-08 19:08 UTC, lev4rT commented
Честно сказать не вижу смысла проверять древнейший код, думаю стоит влить и прогонять уже свежее.

2021-03-08 20:14 UTC, tmible approved these changes

2021-03-08 20:16 UTC, tmible commented
Вливай дев и асигни меня. Но за объект в конструкторе обидно(

2021-03-08 20:57 UTC, merged