Validator fix + small fix on unloginned add product
frontend-park-mail-ru/2021_1_DuckLuck pull request #87
Opened 2021-05-25 20:48 UTC by lev4rT

Пофиксил валидатор. Теперь он обрабатывает ответы от сервера + небольшой фикс при добавлении продукта незалогиненным пользователем с последующей авторизацией

2021-05-25 21:08 UTC, tmible requested changes

2021-05-25 21:08 UTC, tmible commented on ozon/src/modules/Valiadtor/validator.js
> +        result.failedFields.push(fields.repeatPasswordTooLong);
Они же не синхронизируются

2021-05-25 22:16 UTC, lev4rT commented on ozon/src/modules/Valiadtor/validator.js
> +        result.failedFields.push(fields.repeatPasswordTooLong);
Вот тут хз как лучше с точки зрения пользовательского опыта. Изменил так, чтобы в случае ошибки основного пароля сбрасывался только он

2021-05-25 22:20 UTC, lev4rT commented on ozon/src/modules/Valiadtor/validator.js
> +        result.failedFields.push(fields.repeatPasswordTooLong);
Хотя не, наверно лучше и повтор пароля сбрасывать

2021-05-26 09:23 UTC, tmible approved these changes

2021-05-26 09:23 UTC, merged